name: CI Pipeline

# Trigger workflow on push to dev/main OR PR targeting dev/main
on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 4️⃣ Run tests
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
